---
- name: Install Docker prerequisites
  apt:
    name: "{{ docker_prerequisites }}"
    state: present

- name: Add Docker GPG key
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
    gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg
  become: true

- name: Add Docker repository
  become: true
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename | default('noble') }} stable
    owner: root
    group: root
    mode: '0644'

- name: Update apt cache after adding Docker repo
  apt:
    update_cache: yes

- name: Install Docker Engine and Compose plugin
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes
  become: true

- name: Ensure Docker service is enabled and started
  service:
    name: docker
    state: started
    enabled: yes
  become: true