---
- name: Set Python source directory
  set_fact:
    python_src_dir: "/tmp/Python-{{ python_version }}"

- name: Download Python source archive
  get_url:
    url: "{{ python_src_url }}"
    dest: "/tmp/Python-{{ python_version }}.tgz"
    mode: '0644'

- name: Extract Python source
  unarchive:
    src: "/tmp/Python-{{ python_version }}.tgz"
    dest: /tmp
    remote_src: yes
    creates: "{{ python_src_dir }}"

- name: Configure Python build
  command: ./configure --enable-optimizations
  args:
    chdir: "{{ python_src_dir }}"
    creates: "{{ python_src_dir }}/Makefile"

- name: Build Python
  command: make -j{{ ansible_processor_vcpus | default(2) }}
  args:
    chdir: "{{ python_src_dir }}"

- name: Install Python using altinstall
  command: make altinstall
  args:
    chdir: "{{ python_src_dir }}"
  become: true